import { writeFileSync } from "fs";
import { ethers } from "hardhat";

const MY3SEC_TOKEN_INITIAL_SUPPLY = 10000000;
const SKILL_REGISTRY_BASE_URI = "https://my3sec.vaimee.com/skills/";

async function main() {
  // Factories
  const my3secHubFactory = await ethers.getContractFactory("My3SecHub");
  const organizationFactoryFactory = await ethers.getContractFactory("OrganizationFactory");
  const my3secTokenFactory = await ethers.getContractFactory("My3SecToken");
  const skillRegistryFactory = await ethers.getContractFactory("SkillRegistry");
  const my3secProfilesFactory = await ethers.getContractFactory("My3SecProfiles");
  const energyWalletFactory = await ethers.getContractFactory("EnergyWallet");
  const timeWalletFactory = await ethers.getContractFactory("TimeWallet");
  const skillWalletFactory = await ethers.getContractFactory("SkillWallet");

  // Deployments
  console.log("\n\t-- Deploying My3SecHub --");
  const my3secHub = await my3secHubFactory.deploy();

  console.log("\n\t-- Deploying OrganizationFactory --");
  const organizationFactory = await organizationFactoryFactory.deploy();

  console.log("\n\t-- Deploying My3SecToken --");
  const my3secToken = await my3secTokenFactory.deploy(my3secHub.address, MY3SEC_TOKEN_INITIAL_SUPPLY);

  console.log("\n\t-- Deploying SkillRegistry --");
  const skillRegistry = await skillRegistryFactory.deploy(SKILL_REGISTRY_BASE_URI);

  console.log("\n\t-- Deploying My3SecProfiles --");
  const my3secProfiles = await my3secProfilesFactory.deploy(my3secHub.address);

  console.log("\n\t-- Deploying EnergyWallet --");
  const energyWallet = await energyWalletFactory.deploy(my3secHub.address);

  console.log("\n\t-- Deploying TimeWallet --");
  const timeWallet = await timeWalletFactory.deploy(my3secHub.address);

  console.log("\n\t-- Deploying SkillWallet --");
  const skillWallet = await skillWalletFactory.deploy(my3secHub.address);

  // Initializations
  console.log("\n\t-- Initializing My3SecHub --");
  await my3secHub.setOrganizationFactoryContract(organizationFactory.address);
  await my3secHub.setSkillRegistryContract(skillRegistry.address);
  await my3secHub.setMy3SecProfilesContract(my3secProfiles.address);
  await my3secHub.setEnergyWalletContract(energyWallet.address);
  await my3secHub.setTimeWalletContract(timeWallet.address);
  await my3secHub.setSkillWalletContract(skillWallet.address);

  // Save and logs addresses
  const addrs = {
    my3secHub: my3secHub.address,
    organizationFactory: organizationFactory.address,
    my3secToken: my3secToken.address,
    skillRegistry: skillRegistry.address,
    my3secProfiles: my3secProfiles.address,
    energyWallet: energyWallet.address,
    timeWallet: timeWallet.address,
    skillWallet: skillWallet.address,
  };
  const json = JSON.stringify(addrs, null, 2);
  console.log(json);

  writeFileSync("./deployed.json", json, "utf-8");
  writeFileSync("./DEPLOYED.md", buildDocumentation(addrs), "utf-8");
}

function buildDocumentation(deployed: Record<string, string>) {
  const maxKeyLength = Object.keys(deployed).reduce((acc, key) => {
    return key.length > acc ? key.length : acc;
  }, 0);

  /* eslint-disable prettier/prettier */
  const mainBody = `
  # My3Sec Contracts
  > **Note:** this file is auto generated by the \`deploy.ts\` script. Do not edit it manually.

  The following contracts have been deployed in the Bellecour network:

  | ${"Contract".padEnd(maxKeyLength," ")} | Address                                                                                                                                           |
  | ${"-------".padEnd(maxKeyLength, "-")} | ------------------------------------------------------------------------------------------------------------------------------------------------- |
`;

  const tableBody = Object.keys(deployed).reduce((acc, key) => {
    const contract = (key.charAt(0).toUpperCase() + key.slice(1)).padEnd(maxKeyLength, " ");
    return (      
      acc + `  | ${contract} | [${deployed[key]}](https://blockscout-bellecour.iex.ec/address/${deployed[key]}/transactions) |` + "\n"
    );
  }, "");
  /* eslint-enable prettier/prettier */
  const footer = "\n" + `*source: [deployed.json](./deployed.json)*` + "\n";
  return mainBody + tableBody + footer;
}
// We recommend this pattern to be able to use async/await everywhere
// and properly handle errors.
main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
