export function buildDocumentation(deployed: Record<string, string>) {
  const maxKeyLength = Object.keys(deployed).reduce((acc, key) => {
    return key.length > acc ? key.length : acc;
  }, 0);

  /* eslint-disable prettier/prettier */
    // prettier-ignore
    const mainBody = `
  # My3Sec Contracts
  > **Note:** this file is auto generated by the \`deploy.ts\` script. Do not edit it manually.

  The following contracts have been deployed in the Bellecour network:

  | ${"Contract".padEnd(maxKeyLength, " ")} | Address                                                                                                                                           |
  | ${"-------".padEnd(maxKeyLength, "-")} | ------------------------------------------------------------------------------------------------------------------------------------------------- |
`;

    const tableBody = Object.keys(deployed).reduce((acc, key) => {
        const contract = (key.charAt(0).toUpperCase() + key.slice(1)).padEnd(maxKeyLength, " ");
        return (
            // prettier-ignore
            acc + `  | ${contract} | [${deployed[key]}](https://blockscout-bellecour.iex.ec/address/${deployed[key]}/transactions) |` + "\n"
        );
    }, "");
    /* eslint-enable prettier/prettier */
  const footer = "\n" + `*source: [deployed.json](./deployed.json)*` + "\n";
  return mainBody + tableBody + footer;
}
