# This is a basic workflow to help you get started with Actions

name: Contracts

on:
  push:
    branches: [ "main" ]
    paths:
      - "protocol/**"
      - ".github/workflows/contracts.yml"
    tags:
      - "v*-contracts"   
  pull_request:
    branches: [ "main" ]
    paths:
      - "protocol/**"
      - ".github/workflows/contracts.yml"
  workflow_dispatch:

defaults:
 run:
  working-directory: ./protocol
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.3.0
      - run: npm ci
      - run: npm run build
  unit:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.3.0
      - run: npm ci
      - run: npm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.3.0
      - run: npm ci
      - run: npm run lint
  deploy:
    runs-on: ubuntu-latest
    needs: [build, unit, lint]
    if: startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      # TODO: find a way to not rebuild
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

