# This is a basic workflow to help you get started with Actions

name: Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"
    tags:
      - "v*-frontend"
  pull_request:
    branches: [ "main" ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"
  workflow_dispatch:

defaults:
 run:
  working-directory: ./frontend
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.3.0
      - run: npm ci
      - run: npm run build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.3.0
      - run: npm ci
      - run: npm run lint
  deploy:
    runs-on: ubuntu-latest
    needs: [build, lint]
    if: startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ github.event.ref }}
      
