name: Landing

on:
  push:
    branches: ["main"]
    paths:
      - "landing/**"
      - ".github/workflows/landing.yml"
    tags:
      - "v*-landing"
  pull_request:
    branches: ["main"]
    paths:
      - "landing/**"
      - ".github/workflows/landing.yml"
  workflow_dispatch:

defaults:
  run:
    working-directory: ./landing
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.3.0
      - run: npm ci
      - name: Build the project
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: vaimee/my3sec-landing:${{github.ref_name}},vaimee/my3sec-landing:latest
          context: ./landing